<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_help().
 */
function ip_viewer_help($path, $arg) {
  if ($path == 'admin/help#ip_viewer') {
    $content = '<p>' . t('The IP Viewer module logs the IP address of users whenever they log in. This module is intended to help identify spammers and make blocking their IP addresses easier for administrators.') . '</p>';

    return $content;
  }
}

/**
 * Implements hook_menu().
 */
function ip_viewer_menu() {
  $items = array();

  return $items;
}

/**
 * Implements hook_permission().
 */
function ip_viewer_permission() {
  return array(
    'access user ip addresses' => array(
      'title' => t('Access user IP addresses'),
      'description' => t('Allows user login IP addresses'),
      'restrict access' => TRUE,
    ),
  );
}