<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_help().
 */
function ip_viewer_help($path, $arg) {
  if ($path == 'admin/help#ip_viewer') {
    $content = '<p>' . t('The IP Viewer module logs the IP address of users whenever they log in. This module is intended to help identify spammers and make blocking their IP addresses easier for administrators.') . '</p>';

    return $content;
  }
}

/**
 * Implements hook_menu().
 */
function ip_viewer_menu() {
  $items = array();

  $items['admin/people/ip-addresses'] = array(
    'title' => t('User IP Addresses'),
    'page callback' => 'ip_viewer_list_form',
    'file' => 'ip_viewer.admin.inc',
    'access arguments' => array('access user ip addresses'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ip_viewer_permission() {
  return array(
    'access user ip addresses' => array(
      'title' => t('Access user IP addresses'),
      'description' => t('Allows user login IP addresses'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ip_viewer_form_system_ip_blocking_form_alter(&$form, &$form_state, $form_id) {
  if (isset($_GET['ip']) && ctype_digit($_GET['ip']) ) {
    $ip = db_select('ip_viewer', 'i')
      ->fields('i', array('ip_address'))
      ->condition('i.ipid', urldecode($_GET['ip']), '=')
      ->execute();

    $form['ip']['#default_value'] = $ip->fetchField();
    // $form['destination'] = drupal_get_destination();
  }
}

/*
 * Include file with all user related hook implementations.
 */
require_once dirname( __FILE__ ) . '/ip_viewer.user.inc';